export const projects = [
  {
    title: 'ThinToken',
    description:"Developed an RFID-based physical 2FA system called ThinToken. Our thesis evaluated ThinToken and Yubikey in terms of time-based efficiency, and usability. The researchers found that ThinToken outperformed Yubikey in all these aspects.",
    image: '/images/thintoken.png',
    tags: ['C++', 'JavaScript', 'RFID', 'ESP32'],
    source: 'https://github.com/orgs/Group4-ThinToken/repositories',
    visit: '/Thesis Thintoken IEEE.pdf',
    id: 0,
  },
  {
    title: 'iAssess',
    description: "The Online Self Assessment Web Application for TESDA's Computer Systems Servicing NCII",
      image: '/images/iassess.jpg',
      tags: ['HTML', 'CSS', 'Bootstrap', 'JavaScript'],
    source: 'https://github.com/proDev-Theron/iASSESS',
    visit: 'https://prodev-theron.github.io/iASSESS/',
    id: 1,
  },
  {
    title: 'Medicall',
    description: "A Static Website for a Pharmacy. Primary Focus in doing this project is to learn more about Project Management, Source-Code Management and Developer Collaboration.",
      image: '/images/medicall-ls-1.png',
      tags: ['HTML', 'Bootstrap', 'JavaScript'],
    source: 'https://github.com/PLM-CPE0326-ELECTIVES-2022/CA-2-BLOCK-1-RC',
    visit: '/Medicall.pdf',
    id: 2,
  },
  {
    title: 'IVSHS School Website and Learning Management System',
    description: "Created using WordPress and Elementor Plugin. Bought the domain name, Hosted and Deployed on GoDaddy. With the LMS, you can create and manage Grades, Courses, Sections, Lessons, and others.",
    image: '/images/ivshs.com.jpg',
    tags: ['WordPress', 'Elementor', 'PHP'],
    source: '',
    visit: 'http://www.ivshs.com/new-home',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2013, text: 'Wrote my first "Hello, World!"', },
  { year: 2018, text: 'Started Freelancing', },
  { year: 2019, text: 'Took BS Computer Engineering in College', },
  { year: 2020, text: 'Worked with student-led organizations during the pandemic', },
  { year: 2021, text: 'Became one of the 10 Filipino Scholars of ULAP.org', },
  { year: 2022, text: 'Got cloud professional certifications from Microsoft, AWS, and Alibaba Cloud', },
  { year: 2023, text: 'Finished College and now plays guitar while not coding', },
];

export const certifications = [
  {
    title: 'AWS Certified Cloud Practitioner',
    description: "Demonstrated cloud fluency and understanding of essential IT services and their uses on AWS Cloud. Thoroughly prepared for the certification by training with AWS User Group Manila and graduating from AWS Academy.",
    image: '/images/cert-aws-cloud-practitioner.png',
    details: 'https://aws.amazon.com/certification/certified-cloud-practitioner/',
    verify: 'https://www.credly.com/badges/470b7fbd-aa3f-4b81-9b49-79fb1aad237a',
    id: 0,
  },
  {
    title: 'Google IT Support Professional Certificate',
    description: "Acquired Google IT Support Certificate with hands-on practice-based assessments in troubleshooting, customer service, networking, operating systems, system administration, and security.",
    image: '/images/GCC_badge_IT_Support_1000x1000.png',
    details: 'https://www.coursera.org/professional-certificates/google-it-support',
    verify: 'https://www.credly.com/badges/86aaa5c8-c180-493a-aa38-cc1a13f505c6',
    id: 1,
  },
  {
    title: 'Microsoft Certified: Azure Fundamentals (AZ-900)',
    description: "Exhibited knowledge and proficiency of cloud services and how those services are provided with Microsoft Azure.",
    image: '/images/cert-az-900.png',
    details: 'https://learn.microsoft.com/api/credentials/share/en-us/THERONBUENO/95C7A50D87072055?sharingId=AF0FB8BD620CCCAF',
    verify: 'https://www.credly.com/badges/965c94df-1bd4-47e1-9849-af99fed184bc/',
    id: 2,
  },
  {
    title: 'Google Cloud Platform Badges',
    description: "Completed Infrastructure Modernization and Application Development hands-on courses and solved challenges by Google Developer Group Manila.",
    image: '/images/3.jpg',
    details: 'https://gdsc.community.dev/events/details/developer-student-clubs-pamantasan-ng-lungsod-ng-maynila-presents-gcpinas-learn-google-cloud-platform/',
    verify: 'https://www.cloudskillsboost.google/public_profiles/fd703a21-4c34-4212-9eee-abcd170a320b',
    id: 3,
  },
  {
    title: 'ACP Cloud Computing',
    description: "ACP Cloud Computing Certification is designed for those familiar to cloud computing and with a rich operational knowledge of Alibaba Cloud products. This certification covers a spectrum of Alibaba Cloud core services, including architecture, networking, cloud security, and best practices.",
    image: '/images/2.png',
    details: 'https://edu.alibabacloud.com/certification/acp_cloudcomputing',
    verify: 'https://xuecdn2.aliyunedu.net/img_d3cf62db918f82d25cc68a511e3502bc.png',
    id: 4,
  },
  {
    title: 'ACA Developer Certification',
    description: "Alibaba Developer Certification is designed for individuals who hold development positions and use Alibaba Cloud products to manage and maintain Alibaba Cloud-based applications.",
    image: '/images/1.png',
    details: 'https://edu.alibabacloud.com/certification/aca_developer',
    verify: 'https://xuecdn2.aliyunedu.net/img_eec4a5efdc15ad52c8bb1c4955d885ef.png',
    id: 5,
  },
];